mysql:
  image: mysql:5.7
  container_name: starter_databse
  ports:
    - 4800:3306

  environment:
    MYSQL_DATABASE: starter_laravel
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_PASSWORD: secret


php:
  image: php:fpm-alpine
  container_name: starter_php
  volumes:
    - .:/var/www/lara-docker-starter
  entrypoint:
    - php-fpm

nginx:
  image: nginx:alpine
  container_name: starter_nginx
  volumes_from:
    - php
  volumes:
    - .:/var/www/lara-docker-starter
    - ./build/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php
  ports:
    - 8080:80

phpmyadmin:
    links:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: starter_phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
