mysql:
  image: mysql
  container_name: databse
  ports:
    - 4800:3306

  environment:
    MYSQL_DATABASE: laravel
    MYSQL_ROOT_PASSWORD: secret


php:
  image: php:fpm-alpine
  container_name: php
  volumes:

    - .:/var/www/lara-docker-starter
  entrypoint:

    - php-fpm

nginx:
  image: nginx:alpine
  container_name: nginx
  volumes_from:
    - php
  volumes:
    - .:/var/www/lara-docker-starter
    - ./build/nginx.conf:/etc/nginx/conf.d/default.conf

  links:
    - php

  ports:
    - 8080:80

phpmyadmin:
    links:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
